### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by kisyular** [kisyular/MI-449-SS17-740-html-meta-elements-_f2DoK#1]
@KatieMFritz Can you take a look at this? It's [hosted here](https://kisyular-kapv98gmwdanx_f2dok.surge.sh/) and meets the following criteria:

- [x] Include a homepage and at least one other page, for your best-selling T-shirt (you can download a T-shirt image [from ThinkGeek](http://www.thinkgeek.com/clothing/t-shirts/))
- [x] A language is specified for the website (it does _not_ have to be in English!)
- [x] A `title` and `meta name="description"` are provided for each page
- [x] Every page includes a link to a `favicon.ico` file with the company logo (you can [create one here](https://www.hipsterlogogenerator.com/) or design one yourself)
- [x] Location information is provided on every page (you can place the store anywhere in the world, as long as there's an existing building there)
- [x] When each page is shared on Facebook and Twitter, a beautiful card is generated (and the [respective](https://developers.facebook.com/tools/debug/sharing/) [validators](https://cards-dev.twitter.com/validator) should return no errors/warnings -- though you can ignore the `Share App ID Missing` warning for Facebook)

I had an issue with my favicon. On my Local Server (Live-Server) I can see the favicon, however, on surge server, the favicon disappears.
![screen shot 2017-03-15 at 02 27 23](https://cloud.githubusercontent.com/assets/15636554/23936189/f7ddf3b4-0926-11e7-8533-576bf1b55bb4.png)

**Comment by KatieMFritz** [comment]
Hi Rellikson, I can see your favicon. It might have been a caching issue or something. Can you see it if you look now?

I like your shirts. 😄 

### Valid HTML
There are a couple errors for your site in the [W3 Validator](https://validator.w3.org/nu/?doc=https%3A%2F%2Fkisyular-kapv98gmwdanx_f2dok.surge.sh%2F). Please fix them and be sure to check with that tool before submitting future projects!

### Fix Open Graph errors/warnings
I'm seeing warnings when I validate your site in the [open graph debugger](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fkisyular-kapv98gmwdanx_f2dok.surge.sh%2F) too.

### Other things to check
Please make sure you're not getting any W3C errors, Atom linter errors (HTML or CSS), JS console errors, Open Graph validator error/warnings, or Twitter validator errors/warnings when you resubmit. Also put your geo coordinates for the site into Google maps and make sure they show a building.

Let me know when you've checked all that and resubmitted! 😄

**Comment by kisyular** [comment]
@KatieMFritz, I have made the necessary changes you suggested. I have passed my Website through W3 Validator and no errors this time. The FaceBook Debugger also did not give me errors. I have also made sure that the geolocation is on top of a Building (McDonel Hall).

Thank you

**Comment by KatieMFritz** [comment]
Good job addressing the errors. 🌟 😄 

### Consistent spacing
There are some big gaps between lines in your HTML files.  It's helpful to use single line breaks to group your code (you've done that well in several places), but more than that looks like a mistake and makes me distrust your code. 😝 Take a pass through your code and make the line spacing more consistent, please.

* * *
### Unique title & description for each page
Now that you're not getting errors, let's take your metadata to the next level. 🚀 

Here are some guildeines for writing titles and descriptions for your pages (including `title` and `meta name="description` elements, Twitter metadata, and Facebook (`og`) metadata:

1. **Each page should have a _unique_ title and description that describes that specific page** for people who have no idea what your site is about (because they will see this info on social media or search results before they ever come to your site). From the lesson: 

    > [It's] common for homepages to describe the entire website. On every other page however, this information should be specific to the current page.

2. **Each page should (usually) have _consistent_ titles and descriptions across platforms,** i.e. the Twitter, Open Graph, and general titles and descriptions should all match each other. This helps users figure out whether they've already visited that page. It also makes life easier for you - you can just copy and paste! Once you get into more advanced site development, you can use the same variables across all three places.

3. **Titles and descriptions should be brief.** Different platforms display different amounts of text, but I usually use [50-70 characters for titles, 100-150 characters for descriptions](http://www.thesempost.com/new-title-description-lengths-for-google-seo/). Anything longer will likely get cut off.
 * * *
If you have questions about any of this, I'll be on Slack most of Monday! 😄

**Comment by kisyular** [comment]
@KatieMFritz 
Fixed the inconsistent spacing. Gave each page a unique title. The page title is also applied to facebook and twitter

**Comment by KatieMFritz** [comment]
Almost! I like how you used similar vocabulary for both pages, to keep your branding consistent and improve your SEO, but gave each page a unique title and description. 👍 😄 

If you look at the [Open Graph debugger for your "second" page](https://developers.facebook.com/tools/debug/sharing/?q=https%3A%2F%2Fkisyular-kapv98gmwdanx_f2dok.surge.sh%2Fsecond), you'll see it shows the same information as the home page. That's because you didn't update the `og:url` property for that page. 🦑 

Regarding spacing, it looks much better! You can get rid of the blank first line of each HTML page though. It's unnecessary. Did your HTML linter give you any warnings about that?

**Comment by kisyular** [comment]
@KatieMFritz 

1. I have fixed the space at the top. Although linter did not give any warning or errors. See screenshot below.
![screen shot 2017-03-21 at 11 31 30](https://cloud.githubusercontent.com/assets/15636554/24155755/1184a61a-0e2b-11e7-9e4b-067e118ec6db.png)
2. I have changed the og:url
 to match to [Second Page]( https://kisyular-kapv98gmwdanx_f2dok.surge.sh/second/index.html)

**Comment by KatieMFritz** [comment]
Thanks for the screenshot! 😄 

Great job with this. :boom: :shipit:
